### ISSUE TITLE
Via v-3 compatibility

### ISSUE THREAD

**Issue by ProHaller** [ormcat/keybord_ergo_fine#1]
The V2 of via returns a few errors when loading the profile. And the V3 doesn't load. It would be super useful to allow for better compatibility. 
```

07:08:13.028
Command Name: BACKLIGHT_CONFIG_GET_VALUE
Command: 8 128
Response: 255 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.040
Error: Receiving incorrect response for command
at KeyboardAPI._hidCommand (https://usevia.app/assets/index-57542d2d.js:3:9407)
at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-57542d2d.js:3:8661)
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.050
Loading lighting/menu data failed
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.060
Command Name: BACKLIGHT_CONFIG_GET_VALUE
Command: 8 129
Response: 255 129 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.067
Error: Receiving incorrect response for command
at KeyboardAPI._hidCommand (https://usevia.app/assets/index-57542d2d.js:3:9407)
at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-57542d2d.js:3:8661)
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.079
Command Name: BACKLIGHT_CONFIG_GET_VALUE
Command: 8 130
Response: 255 130 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.086
Error: Receiving incorrect response for command
at KeyboardAPI._hidCommand (https://usevia.app/assets/index-57542d2d.js:3:9407)
at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-57542d2d.js:3:8661)
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.095
Command Name: BACKLIGHT_CONFIG_GET_VALUE
Command: 8 131
Response: 255 131 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546

07:08:13.103
Error: Receiving incorrect response for command
at KeyboardAPI._hidCommand (https://usevia.app/assets/index-57542d2d.js:3:9407)
at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-57542d2d.js:3:8661)
Device: ErgoFine Keyboard
Vid: 0x4F45
Pid: 0x4546
```

Thank you for your work and awesome keyboard.

**Comment by ormcat** [comment]
I don't have this keyboard now, and  I can't verify the actual machine when update firmware.
Therefore, we are very sorry, but I  cannot update the firmware.
Publishing firmware that I know won't work is a bad idea.

If someone develops a firmware and makes a pull request, I will accept it.

thank you.
